import { SchemaAST, MigrationRequest, MigrationArtifact, RiskReport } from './interfaces';

/**
 * Migration Generator - Generates SQL migrations based on change requests
 */
export class MigrationGenerator {
  /**
   * Generate a migration artifact based on the request and risk report
   * @param request - The migration request
   * @param riskReport - The analyzed risk report
   * @returns MigrationArtifact with SQL, rollback SQL, and metadata
   */
  public generate(request: MigrationRequest, riskReport: RiskReport): MigrationArtifact {
    const sql = this.generateSql(request, riskReport);
    const rollbackSql = this.generateRollbackSql(request);
    const filename = this.generateFilename(request.changeDescription);
    
    return {
      sql,
      rollbackSql,
      filename,
      generatedAt: new Date().toISOString(),
      summary: this.generateSummary(request.changeDescription),
      warnings: riskReport.warnings
    };
  }

  /**
   * Generate the main migration SQL
   */
  private generateSql(request: MigrationRequest, riskReport: RiskReport): string {
    const changeDesc = request.changeDescription.toLowerCase();
    let sql = '-- Migration generated by DB Migration Architect Agent\n';
    sql += `-- Risk Level: ${riskReport.riskLevel}\n`;
    sql += `-- Overall Risk Score: ${riskReport.overallScore}/100\n\n`;

    // Add pre-flight assertions for high-risk migrations
    if (riskReport.overallScore > 50) {
      sql += this.generatePreFlightAssertions(request) + '\n\n';
    }

    // Pattern selection based on change description
    if (changeDesc.includes('add column')) {
      sql += this.generateAddColumnSql(request);
    } else if (changeDesc.includes('drop column')) {
      sql += this.generateDropColumnSql(request);
    } else if (changeDesc.includes('add index') || changeDesc.includes('create index')) {
      sql += this.generateAddIndexSql(request, riskReport);
    } else if (changeDesc.includes('drop index')) {
      sql += this.generateDropIndexSql(request);
    } else if (changeDesc.includes('add foreign key')) {
      sql += this.generateAddForeignKeySql(request, riskReport);
    } else if (changeDesc.includes('change type') || changeDesc.includes('alter column')) {
      sql += this.generateAlterColumnSql(request, riskReport);
    } else {
      sql += `-- TODO: Implement specific SQL for: ${request.changeDescription}\n`;
      sql += '-- Please review and complete the migration manually.\n';
    }

    return sql;
  }

  /**
   * Generate rollback SQL
   */
  private generateRollbackSql(request: MigrationRequest): string {
    const changeDesc = request.changeDescription.toLowerCase();
    let sql = '-- Rollback migration generated by DB Migration Architect Agent\n\n';

    if (changeDesc.includes('add column')) {
      sql += this.generateDropColumnSql(request);
    } else if (changeDesc.includes('drop column')) {
      sql += `-- WARNING: Dropping a column is destructive. Manual data restoration may be required.\n`;
      sql += `-- TODO: Implement column restoration for: ${request.changeDescription}\n`;
    } else if (changeDesc.includes('add index') || changeDesc.includes('create index')) {
      sql += this.generateDropIndexSql(request);
    } else if (changeDesc.includes('drop index')) {
      sql += this.generateAddIndexSql(request, { overallScore: 0, riskLevel: 'LOW' } as RiskReport);
    } else if (changeDesc.includes('add foreign key')) {
      sql += this.generateDropForeignKeySql(request);
    } else if (changeDesc.includes('change type') || changeDesc.includes('alter column')) {
      sql += `-- WARNING: Reverting type changes may result in data loss.\n`;
      sql += `-- TODO: Implement type reversion for: ${request.changeDescription}\n`;
    } else {
      sql += `-- TODO: Implement specific rollback SQL for: ${request.changeDescription}\n`;
      sql += '-- Please review and complete the rollback manually.\n';
    }

    return sql;
  }

  /**
   * Generate a timestamped filename for the migration
   */
  private generateFilename(changeDescription: string): string {
    const now = new Date();
    const timestamp = now.toISOString().replace(/[-:T.]/g, '').slice(0, 14); // YYYYMMDDHHMMSS
    const cleanDesc = changeDescription
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_|_$/g, '')
      .slice(0, 50); // Limit length
    
    return `${timestamp}_${cleanDesc}.sql`;
  }

  /**
   * Generate a summary of the migration
   */
  private generateSummary(changeDescription: string): string {
    return `Migration: ${changeDescription}`;
  }

  /**
   * Generate pre-flight assertions
   */
  private generatePreFlightAssertions(request: MigrationRequest): string {
    // PostgreSQL specific assertions
    if (request.targetEngine === 'postgres') {
      return `DO $$\nBEGIN\n  -- Pre-flight assertions\n  -- Add specific checks here based on the migration\n  ASSERT true, 'Pre-flight checks passed';\nEND $$;`;
    }
    // MySQL specific assertions (simplified)
    return `-- Pre-flight assertions for MySQL\n-- Add specific checks here based on the migration`;
  }

  /**
   * Pattern: Add Column
   */
  private generateAddColumnSql(request: MigrationRequest): string {
    // Simplified implementation - in reality, this would parse the exact change
    return `-- Pattern: Add Column (Safe)\n-- This operation is generally safe and non-blocking.\nALTER TABLE target_table ADD COLUMN new_column VARCHAR(255);`;
  }

  /**
   * Pattern: Drop Column
   */
  private generateDropColumnSql(request: MigrationRequest): string {
    return `-- Pattern: Drop Column (Destructive)\n-- WARNING: This will permanently remove data.\nALTER TABLE target_table DROP COLUMN target_column;`;
  }

  /**
   * Pattern: Add Index
   */
  private generateAddIndexSql(request: MigrationRequest, riskReport: RiskReport): string {
    if (request.targetEngine === 'postgres' && riskReport.overallScore > 30) {
      return `-- Pattern: Add Index Concurrently (Safe for large tables)\n-- Prevents table locks during index creation.\nCREATE INDEX CONCURRENTLY idx_target_table_column ON target_table (target_column);`;
    }
    return `-- Pattern: Add Index\nCREATE INDEX idx_target_table_column ON target_table (target_column);`;
  }

  /**
   * Pattern: Drop Index
   */
  private generateDropIndexSql(request: MigrationRequest): string {
    return `-- Pattern: Drop Index\nDROP INDEX IF EXISTS idx_target_table_column;`;
  }

  /**
   * Pattern: Add Foreign Key
   */
  private generateAddForeignKeySql(request: MigrationRequest, riskReport: RiskReport): string {
    if (request.targetEngine === 'postgres' && riskReport.overallScore > 40) {
      return `-- Pattern: Add Foreign Key NOT VALID (Safe for large tables)\n-- Adds constraint without scanning existing data.\nALTER TABLE target_table ADD CONSTRAINT fk_target FOREIGN KEY (target_column) REFERENCES referenced_table (id) NOT VALID;\n\n-- Validate in a separate, low-traffic transaction:\n-- ALTER TABLE target_table VALIDATE CONSTRAINT fk_target;`;
    }
    return `-- Pattern: Add Foreign Key\nALTER TABLE target_table ADD CONSTRAINT fk_target FOREIGN KEY (target_column) REFERENCES referenced_table (id);`;
  }

  /**
   * Pattern: Drop Foreign Key
   */
  private generateDropForeignKeySql(request: MigrationRequest): string {
    return `-- Pattern: Drop Foreign Key\nALTER TABLE target_table DROP CONSTRAINT IF EXISTS fk_target;`;
  }

  /**
   * Pattern: Alter Column (Type Change)
   */
  private generateAlterColumnSql(request: MigrationRequest, riskReport: RiskReport): string {
    if (riskReport.overallScore > 50) {
      return `-- Pattern: Expand and Contract (Safe type change)\n-- Step 1: Add new column\nALTER TABLE target_table ADD COLUMN new_column NEW_TYPE;\n\n-- Step 2: Backfill data (requires application logic or trigger)\n-- UPDATE target_table SET new_column = CAST(old_column AS NEW_TYPE);\n\n-- Step 3: Swap columns (requires downtime or complex logic)\n-- ALTER TABLE target_table DROP COLUMN old_column;\n-- ALTER TABLE target_table RENAME COLUMN new_column TO old_column;`;
    }
    return `-- Pattern: Alter Column\nALTER TABLE target_table ALTER COLUMN target_column TYPE NEW_TYPE;`;
  }
}